

POST https://azure-native-spring-function.azurewebsites.net/api/hello?code=fsyf09pdrFCb8u-Dz2Hrx3caHzJFH1PwFBdNhbyqNd_TAzFuX_r8IA%3D%3D
Content-Type: application/json

{

  "message": "test 1234"
}


####
GET localhost:8080/
Content-Type: application/json

{
  "message": "test 1234"
}