

POST https://azure-function-native.azurewebsites.net/api/hello?code=YpvGnVLDrfN0yg7Dr5EHlAZCva-rpevTJsYwbf3WZdGnAzFuU2CcVA%3D%3D
Content-Type: application/json

{

  "message": "test 1234"
}


####
GET localhost:8080/api/
Content-Type: text/plain

{
  "ich bin dumm"
}