name: Build and deploy native image
on:
  push:
    branches:
      - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: graalvm/setup-graalvm@v1
              with:
                java-version: '21'
                distribution: 'graalvm'
                github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build native image
              run: gradle packageDistribution

            - name: deploy to azure function
              id: fa
              uses: Azure/functions-action@v1
              with:
                app-name: azure-native-spring-function
                package: build/dist/azure-native-spring-function.zip
                publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
